#!/bin/bash

service mariadb start

mariadb -u root -e \
    "CREATE DATABASE IF NOT EXISTS ${WORDPRESS_DATABASE}; \
    CREATE USER '${WORDPRESS_USER}'@'%' IDENTIFIED BY '${WORDPRESS_PASSWORD}'; \
    GRANT ALL ON ${WORDPRESS_DATABASE}.* TO '${WORDPRESS_USER}'@'%' IDENTIFIED BY '${WORDPRESS_PASSWORD}'; \
    FLUSH PRIVILEGES;"